### ISSUE TITLE
Error on setContentView

### ISSUE THREAD

**Issue by Tigresss** [nihasKalam07/ProgressButton#2]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference

**Comment by ldt116** [comment]
I think I have the same issue. Log as below
```
                         E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null
                             object reference
                         E      at com.nihaskalam.progressbuttonlibrary.CircularProgressButton.initAttributes(CircularProgressButton.java:246)
                         E      at com.nihaskalam.progressbuttonlibrary.CircularProgressButton.init(CircularProgressButton.java:134)
                         E      at com.nihaskalam.progressbuttonlibrary.CircularProgressButton.<init>(CircularProgressButton.java:123)
```

**Comment by SimonStefan** [comment]
I had the same problem. I fixed it by setting the following attribute in xml:
`android:textSize="14sp"`
